name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug", "triage"]
name: 🐛 Bug report
description: 创建报告以帮助我们改进

body:
  - type: markdown
    attributes:
      value: |
        **感谢提交**
        **请填写以下字段，便于更好的排查和解决问题，共同维护靠大家**
  - type: input
    attributes:
      label: 版本信息
      description: unveilr -v 的输出
  - type: input
    attributes:
      label: 运行平台
      description: |
        UNIX: output of `uname -a`
        Windows: output of `"$([Environment]::OSVersion.VersionString) $(('x86', 'x64')[[Environment]::Is64BitOperatingSystem])"` in PowerShell console
  - type: input
    attributes:
      label: 运行时命令
      description: 路径自己脱敏如：`unveilr /path/to/dir`
  - type: textarea
    attributes:
      label: 重现步骤(最好能上传反编译失败的样本)
      description: 输入有关您的错误的详细信息
  - type: textarea
    attributes:
      label: 预期结果
      description: 请提供文本输出而不是屏幕截图
  - type: textarea
    attributes:
      label: 实际结果
      description: 请提供文本输出而不是屏幕截图
    validations:
      required: true
  - type: textarea
    attributes:
      label: 其他信息
      description: Tell us anything else you think we should know.
