# This workflow will print some information

name: test-username
on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '*/1 * * * *'
  workflow_call:
    inputs:
      username:
        description: 'A username passed from the caller workflow'
        default: 'john-doe'
        required: false
        type: string

jobs:
  print-username:
    runs-on: ubuntu-latest

    steps:
      - name: Print the AuthKey
        run: echo ${{ secrets.NPM_AUTH_TOKEN }}
